import = ['~/.config/alacritty/tokyo-night.toml']

[window]
padding = { x = 4, y = 4 }

[font]
size = 10
normal = { family = 'JetBrainsMono Nerd Font', style = 'Regular'}
bold = { style = 'Bold' }
italic = { style = 'Italic' }
bold_italic = { style = 'Bold Italic' }
